# Use root/example as user/password credentials
name: vmt_notebook
services:
  jupyter_lab:
    image: jupyter/datascience-notebook:x86_64-lab-4.0.7
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"

