services:
  metabase:
    image: metabase/metabase:v0.54.4.3
    container_name: metabase
    hostname: metabase
    # volumes:
    #   - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 3306
      MB_DB_USER: vmt_user
      MB_DB_PASS: root
      MB_DB_HOST: 192.168.0.100
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
