# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo:6.0.8
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin@123
volumes:
  mongodb-data:
    driver: local