# Use root/example as user/password credentials
services:
  mongodb:
    image: mongo:8.0.9-noble
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  db_data:
