services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
    container_name: es01
    networks:
      - elastic
    ports:
      - 9200:9200 
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ~/config/elk/:/usr/share/elasticsearch/config
    mem_limit: 1GB
    environment:
      - ELASTIC_PASSWORD=admin
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.2
    container_name: kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
      - ~/config/elk/:/usr/share/kibana/config
    networks:
      - elastic
    ports:
      - 5601:5601
    depends_on:
      - es
    mem_limit: 1GB
volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local
networks:
  elastic:
    driver: bridge