# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7.40
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: caplever
  
volumes:
  db_data: