#Use postgres/example user/password credentials
services:
  pgdb:
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - pgdb-data:/var/lib/postgresql/data

volumes:
  pgdb-data:
    driver: local