# Use root/example as user/password credentials
version: '3.1'

services:
  cache:
    image: redis:8.0.2-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
volumes:
  redis-data:
    driver: local