# Use root/example as user/password credentials
version: '3.1'

services:
  redis_cache:
    image: redis:7.2.5-alpine
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
volumes:
  redis-data:
    driver: local